### ISSUE TITLE
Libtool check in autogen.sh

### ISSUE THREAD

**Issue by rudolf-bauer** [TLINDEN/pcp#16]
Hi.

First of all: thanks to @TLINDEN for the nice, curvy interface.

In [autogen.sh Line 76](https://github.com/TLINDEN/pcp/blob/master/autogen.sh#L76) there is an availability check for the command `libtoolize`. However, in [Line 106](https://github.com/TLINDEN/pcp/blob/master/autogen.sh#L106) the command `libtool` is used. This seems a bit inconsistent to me, or am I getting something wrong?

Unfortunately, this causes a `libtoolize: command not found` error on OSX 10.11.5 El Capitan, since the `libtool` package shipped by Xcode does not provide a `libtoolize` command. I had to add a symlink to get it working:

`ln -s /usr/bin/libtool /usr/bin/libtoolize`

Suggestion: Is it possible to simply change the check to `libtool` in Line 76? This would work on ubuntu/debian, too. However, I'm not very familiar with `libtool` and `libtoolize` and their differences.

Additionally, the installation documentation does not contain the execution of `autogen.sh` before running `configure`. Probably just unintentionally missed out?

Thx in advance

**Comment by TLINDEN** [comment]
Hi,

> Suggestion: Is it possible to simply change the check to libtool in Line 76?
> This would work on ubuntu/debian, too. However, I'm not very familiar with
> libtool and libtoolize and their differences.

I'll take a look into that, in fact I can't even remember why there are both used.

> Additionally, the installation documentation does not contain the execution
of autogen.sh before running configure. Probably just unintentionally missed out?

That's why normally such a software is being distributed as a tarball. If I make such a tarball, I execute autogen.sh beforehand. That way a use doesn't need to have autotools installed.

I made some such tarballs but I didn't do it for a long time. So, I'll follow the suggestion and add a section about installing from git.


best,
Tom
